theme = "nord"

[editor]
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# Use Shift-x to unselect lines (or select upwards).
[keys.normal]
A-x = "extend_to_line_bounds"
X = "select_line_above"
[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"
