background			    #090909
foreground			    #f3f2cc
#cursor				    #7e7d6a
selection_background	#404040
selection_foreground	#c4c4c4

# black
color0					#111111
#color8

# white
color7					#f3f2cc
#color15

# red
color1					#f05e48
#color9

# green
color2					#99be70
#color10

# yellow
color3					#fad566
color11					#ffff9f

# blue
color4					#86c1b9
color12					#72a59e

# magenta
color5					#bf74a5
#color13
