#!/usr/bin/env bash

set -euo pipefail

source "$BASH_PATH/restic.bash"

INCLUDE_FILE=/home/fed/fm/env/backup/ava/backup_include
EXCLUDE_FILE=/home/fed/fm/env/backup/ava/backup_exclude
DEVICE=/dev/sdb
DEVICE_NAME=AvaBackup
MOUNT_DIR=/mnt/ava-backup
REPO_LOCAL=$MOUNT_DIR/backups/automatic/home
REPO_REMOTE="sftp:$(pass ava/REMOTE_BACKUP_HOST):backups/automatic/ava/home"

while getopts "hd" opt; do
    case $opt in
        d)
            DRY_RUN=1
            ;;
        h | *)
            echo "Usage: backup [-h] [-d]"
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))

# Clean fm directory first to ensure we don't back up e.g. build artifacts.
clean /home/fed/fm/

# Lock vault before backup.
vault lock

# Unlock LUKS device and mount.
echo "$DISK_PASSWORD" | sudo cryptsetup open $DEVICE $DEVICE_NAME -
sudo mkdir -p $MOUNT_DIR
sudo mount /dev/mapper/$DEVICE_NAME $MOUNT_DIR

# Back up data dir via restic (local).
if [ -v DRY_RUN ]; then
    echo "Starting local dry run..."
    restic -r $REPO_LOCAL --files-from=$INCLUDE_FILE --exclude-file=$EXCLUDE_FILE --dry-run --verbose backup
else
    echo "Starting local restic backup..."
    restic -r $REPO_LOCAL --files-from=$INCLUDE_FILE --exclude-file=$EXCLUDE_FILE --verbose backup
fi

# Unmount and lock LUKS device.
sudo umount $MOUNT_DIR
sudo cryptsetup close $DEVICE_NAME

# Back up data dir via restic/backblaze b2 s3 API (remote).
if [ -v DRY_RUN ]; then
    echo "Starting remote dry run..."
    restic -r $REPO_REMOTE --files-from=$INCLUDE_FILE --exclude-file=$EXCLUDE_FILE --dry-run --verbose backup
else
    echo "Starting remote restic backup..."
    restic -r $REPO_REMOTE --files-from=$INCLUDE_FILE --exclude-file=$EXCLUDE_FILE --verbose backup
fi

