#!/usr/bin/env bash

set -euo pipefail

source "$BASH_PATH/restic.bash"

EXCLUDE_FILE=/home/fed/.backup-exclude
DEVICE=/dev/sdb
DEVICE_NAME=AvaBackup
MOUNT_DIR=/mnt/ava-backup
SRC_DIR=/home/fed/fm
DST_DIR_LOCAL=$MOUNT_DIR/backups/automatic/restic
DST_DIR_REMOTE="s3:s3.$(pass ava/AWS_DEFAULT_REGION).backblazeb2.com/fm-backup-restic"

while getopts "hd" opt; do
    case $opt in
        d)
            DRY_RUN=1
            ;;
        h | *)
            echo "Usage: backup [-h] [-d]"
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))

# Clean source directory first to ensure we don't back up e.g. build artifacts.
clean "$SRC_DIR"

# Lock vault before backup.
vault lock

# Unlock LUKS device and mount.
echo "$DISK_PASSWORD" | sudo cryptsetup open $DEVICE $DEVICE_NAME -
sudo mkdir -p $MOUNT_DIR
sudo mount /dev/mapper/$DEVICE_NAME $MOUNT_DIR

# Back up data dir via restic (local).
if [ -v DRY_RUN ]; then
    echo "Starting local dry run..."
    restic -r $DST_DIR_LOCAL --exclude-file=$EXCLUDE_FILE --dry-run --verbose backup $SRC_DIR
else
    echo "Starting local restic backup..."
    restic -r $DST_DIR_LOCAL --exclude-file=$EXCLUDE_FILE --verbose backup $SRC_DIR
fi

# Unmount and lock LUKS device.
sudo umount $MOUNT_DIR
sudo cryptsetup close $DEVICE_NAME

# Back up data dir via restic/backblaze b2 s3 API (remote).
if [ -v DRY_RUN ]; then
    echo "Starting remote dry run..."
    restic -r $DST_DIR_REMOTE --exclude-file=$EXCLUDE_FILE --dry-run --verbose backup $SRC_DIR
else
    echo "Starting remote restic backup..."
    restic -r $DST_DIR_REMOTE --exclude-file=$EXCLUDE_FILE --verbose backup $SRC_DIR
fi

