#!/usr/bin/env python3

import argparse
import json
import pyutils

parser = argparse.ArgumentParser()
parser.add_argument("url", help="YouTube video URL")
args = parser.parse_args()

print('downloading audio...')
ext = 'flac'
pyutils.sh(f'yt-dlp -x --audio-format {ext} --write-info-json --embed-thumbnail -o "audio.%(ext)s" {args.url}')

print('extracting metadata...')
metadata, _, _ = pyutils.sh('jq .chapters audio.info.json')
metadata_json = json.loads(metadata)
for ch in metadata_json:
    title, start, end = ch['title'], ch['start_time'], ch['end_time']
    print(f'extracting track {title}.ogg...')
    pyutils.sh(f'ffmpeg -nostdin -i audio.{ext} -ss {start} -to {end} -c:a libopus "{title}.ogg"')
