#!/usr/bin/env bash

set -euo pipefail

REPO_LOCAL=/mnt/ava-raid/backups/automatic/home
REPO_REMOTE="sftp:$(pass ava/REMOTE_BACKUP_HOST):backups/automatic/ava/home"

while getopts "hdl" opt; do
    case $opt in
        d)
            dry_run=1
            ;;
        l)
            local_only=1
            ;;
        h | *)
            echo "Usage: homebackup [-h] [-d]"
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))

config="$ENV_PATH/backup/ava_home.bash"

if [ -v dry_run ]; then
    rbackup -r "$REPO_LOCAL" -c "$config" -d
else
    rbackup -r "$REPO_LOCAL" -c "$config"
fi

if [ -v local_only ]; then
    exit 0
fi

if [ -v dry_run ]; then
    rbackup -r "$REPO_REMOTE" -c "$config" -d
else
    rbackup -r "$REPO_REMOTE" -c "$config"
fi

