#!/usr/bin/env sh

NOTES_DIR=/home/fed/documents/notes/

files_and_tags=$(grep -r "tags:.*$" "$NOTES_DIR" | sed 's/tags://g' | sed "s|$NOTES_DIR||g" | sed "s|.md||g")
selected_file_basename=$(echo "$files_and_tags" | fzf -q "$1" | cut -d ':' -f 1)
if [ -n "$selected_file_basename" ]; then
    helix -w "$NOTES_DIR" "$NOTES_DIR/$selected_file_basename.md"
fi
