#!/usr/bin/env bash

set -eo pipefail

# These mime types will be opened via xdg-open instead of vim.
XDG_OPEN_MIME_TYPES=(
    'application/pdf'
    'application/xhtml+xml'
    'text/html'
    'image/jpeg'
    'image/png'
    'image/gif'
    'image/svg'
    'image/svg+xml'
    'audio/mpeg'
    'audio/x-wav'
    'audio/x-vorbis+ogg'
    'audio/x-opus+ogg'
    'video/mp4'
    'video/webm'
)

while getopts "hg" opt; do
    case $opt in
        g)
            USE_GREP=1
            ;;
        h | *)
            echo "Usage: open [-h] [-g] [<path>]"
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))

# If -g option is passed, search by file contents rather than file names.
START_DIR=~
if [ -v USE_GREP ]; then
    if [ -n "$1" ]; then
        if [ -d "$1" ]; then
            START_DIR=$1
        else
            STARTING_QUERY=$1
        fi
    fi
    GREP_FZF_OUTPUT=$(rg -n . "$START_DIR" | fzf -q "$STARTING_QUERY")
    OPEN_PATH=$(echo "$GREP_FZF_OUTPUT" | cut -d: -f1)
    LINE_NUM=$(echo "$GREP_FZF_OUTPUT" | cut -d: -f2)
# If directory argument is specified, interpret as starting directory (default
# to home otherwise). If file argument is specified, open it directly either
# via xdg-open or nvim. If argument is neither a valid file nor directory,
# start a search in home directory using the argument as the starting query.
elif [ -n "$1" ]; then
    if [ -d "$1" ]; then
        START_DIR=$1
    elif [ -f "$1" ]; then
        OPEN_PATH=$1
    else
        STARTING_QUERY=$1
    fi
fi

# Get the path to the file/directory to be opened via fzf, if not already
# specified. Skip this if the grep (-g) option was passed, as we want to avoid
# the user exiting the grep fzf early and then initiating this fzf as well.
if [ -z "$OPEN_PATH" ] && [ ! -v USE_GREP ]; then
    OPEN_PATH=$(fd . "$START_DIR" | fzf --preview='bat --color=always {}' -q "$STARTING_QUERY")
fi

# If the path is empty (e.g. fzf exited early), exit early.
if [ -z "$OPEN_PATH" ]; then
    exit 0
fi

if [ -d "$OPEN_PATH" ]; then
    # Open directories via graphical file explorer.
    xdg-open "$OPEN_PATH"
else
    # For files, check mime type to see whether we should open it via xdg-open.
    OPEN_PATH_MIME_TYPE=$(xdg-mime query filetype "$OPEN_PATH")
    for ((i=0;i<${#XDG_OPEN_MIME_TYPES[@]};i++)); do
        if [ "$OPEN_PATH_MIME_TYPE" = "${XDG_OPEN_MIME_TYPES[${i}]}" ]; then
            xdg-open "$OPEN_PATH"
            exit 0
        fi
    done

    # If not an xdg-open mime type, just open in vim by default. Open at given
    # line number if applicable.
    if [ -v LINE_NUM ]; then
        nvim "+$LINE_NUM" "$OPEN_PATH"
    else
        nvim "$OPEN_PATH"
    fi
fi
