#!/usr/bin/env python3

import argparse
import os
import random

DEFAULT_WALLPAPER_DIR = '/home/fed/images/wallpapers'

parser = argparse.ArgumentParser()
parser.add_argument('directory', nargs='?', help='wallpaper directory')
args = parser.parse_args()

start = args.directory if args.directory else DEFAULT_WALLPAPER_DIR
choices = []
for root, dirs, files in os.walk(start):
    for file in files:
        choices.append(os.path.join(root, file))
wallpaper = random.choice(choices)

os.system(f'gsettings set org.gnome.desktop.background picture-uri-dark file://{wallpaper}')
