#!/usr/bin/env bash

set -euo pipefail

source "$BASH_PATH/restic.bash"

MOUNT_DIR=/mnt/ava-raid
REPO=$MOUNT_DIR/backups/automatic/home
TARGET=/home/fed/home-restore

# Restore from restic backup.
restic -r $REPO --verbose restore latest --target $TARGET
