#!/usr/bin/env bash

set -euo pipefail

BACKUP_INFO=/home/fed/.backup-info
DEVICE=/dev/sdb
DEVICE_NAME=AvaBackup
MOUNT_DIR=/mnt/ava-backup
SRC_DIR=$MOUNT_DIR/backups/automatic/restic
DST_DIR=/home/fed/fm-restore

source <(sudo cat $BACKUP_INFO)

# Unlock LUKS device and mount.
echo $DISK_PASSWORD | sudo cryptsetup open $DEVICE $DEVICE_NAME -
sudo mkdir -p $MOUNT_DIR
sudo mount /dev/mapper/$DEVICE_NAME $MOUNT_DIR

# Restore from restic backup.
restic -r $SRC_DIR --verbose restore latest --target $DST_DIR

# Unmount and lock LUKS device.
sudo umount $MOUNT_DIR
sudo cryptsetup close $DEVICE_NAME
