#!/usr/bin/env bash

set -euo pipefail

WHISPER_MODEL=/usr/share/whisper.cpp-model-large/large.bin

if [ "$#" -ne 2 ]; then
    echo "Usage: transcribe <input audio file path> <output transcription file path>"
    exit 1
fi

input_audio_file_path="$1"
if [ ! -e "$input_audio_file_path" ]; then
    echo "Error: $input_audio_file_path file does not exist"
    exit 1
fi

output_transcription_file_path="$2"
if [ -f "$output_transcription_file_path" ]; then
    echo "Error: $output_transcription_file_path file already exists"
    exit 1
fi

# Convert input audio file to 16 kHz WAV (as required by whisper.cpp).
input_audio_file_name="$(basename "$input_audio_file_path" .m4a)"
tmp_dir="$(mktemp -d)"
wav_audio_file_path="$tmp_dir/$input_audio_file_name".wav
ffmpeg -i "$input_audio_file_path" -ar 16000 -ac 1 -c:a pcm_s16le "$wav_audio_file_path"

# Run whisper.cpp on converted WAV file and output transcription text.
# TODO: whisper.cpp automatically adds .txt extension, possible to change that?
whisper.cpp -t 8 -m "$WHISPER_MODEL" -f "$wav_audio_file_path" --output-txt -of "$output_transcription_file_path"
