#!/usr/bin/env bash

set -euo pipefail

WHISPER_MODEL=/usr/share/whisper.cpp-model-large/large.bin
TRANSCRIPTIONS_DIR=/home/fed/documents/voice_transcriptions/

if [ "$#" -ne 1 ]; then
    echo "Usage: transcribe <audio file path>"
    exit 1
fi

mkdir -p "$TRANSCRIPTIONS_DIR"

# Convert input audio file to 16 kHz WAV (as required by whisper.cpp).
input_audio_file_path="$1"
input_audio_file_name="$(basename "$input_audio_file_path" .m4a)"
tmp_dir="$(mktemp -d)"
wav_audio_file_path="$tmp_dir/$input_audio_file_name".wav
ffmpeg -i "$input_audio_file_path" -ar 16000 -ac 1 -c:a pcm_s16le "$wav_audio_file_path"

# Run whisper.cpp on converted WAV file and output transcription text.
whisper.cpp -t 8 -m "$WHISPER_MODEL" -f "$wav_audio_file_path" --output-txt -of "$TRANSCRIPTIONS_DIR/$input_audio_file_name"
