#!/usr/bin/env python3

import argparse
import gitutils

def main(new_branch, no_set_upstream, no_checkout):
    old_branch = gitutils.current_branch()

    gitutils.git("branch", [new_branch])

    if not no_set_upstream:
        gitutils.git("branch", ["-u", old_branch, new_branch])

    if not no_checkout:
        gitutils.git("checkout", [new_branch])

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("new_branch", help="New branch name")
    parser.add_argument("-u", "--no-set-upstream", help="Don't set upstream", action="store_true")
    parser.add_argument("-c", "--no-checkout", help="Don't checkout new branch", action="store_true")
    args = parser.parse_args()

    gitutils.check_repo()

    main(args.new_branch, args.no_set_upstream, args.no_checkout)
