#!/usr/bin/env python3

import gitutils

import argparse
import sys

NO_UPSTREAM = "{NO_UPSTREAM}"

def colorprint(text, color, bold, no_color):
    if not sys.stdout.isatty() or no_color:
        print(text)
        return

    attr = []
    if color == "red":
        attr.append("31")
    elif color == "cyan":
        attr.append("36")
    elif color == "purple":
        attr.append("35")
    else: # Default to green
        attr.append("32")

    if bold:
        attr.append("1")

    print("\x1b[%sm%s\x1b[0m" % (";".join(attr), text))

def visit(branch, indent, all_branches, upstreams, current_branch, no_color):
    if branch == current_branch:
        colorprint("%s%s *" % (indent, branch), "cyan", True, no_color)
    elif branch == NO_UPSTREAM:
        colorprint("%s%s" % (indent, branch), "purple", False, no_color)
    elif gitutils.is_remote(branch) and not upstreams[branch]:
        colorprint("%s%s" % (indent, branch[8:]), "red", True, no_color)
    else:
        colorprint("%s%s" % (indent, branch), "green", False, no_color)

    children = [b for b in all_branches if upstreams[b] == branch]
    if branch == NO_UPSTREAM:
        children += [b for b in all_branches if not gitutils.is_remote(b) and not upstreams[b]]

    for child in children:
        visit(child, indent + "  ", all_branches, upstreams, current_branch, no_color)

def main(no_color):
    if not gitutils.in_git_repo():
        return

    upstreams = gitutils.upstreams()

    all_branches = set(upstreams.keys())
    current_branch = gitutils.current_branch()

    # Get remote roots
    rootlist = gitutils.remotes()

    # Add local roots
    num_local_roots = sum([b not in rootlist and not upstreams[b] for b in all_branches])
    if num_local_roots > 0:
        rootlist.append(NO_UPSTREAM)

    for root in rootlist:
        visit(root, "", all_branches, upstreams, current_branch, no_color)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-color", help="Turn off colored output", action="store_true")
    args = parser.parse_args()

    main(args.no_color)
