#!/usr/bin/env bash

BACKUP_INFO=/home/fed/.backup-info
DEVICE=/dev/sdb
DEVICE_NAME=AvaBackup
MOUNT_DIR=/mnt/ava-backup
SRC_DIR=/home/fed/fm
DST_DIR_LOCAL=$MOUNT_DIR/backups/automatic/restic
DST_DIR_REMOTE=rclone:gdrive:backups/restic

source <(sudo cat $BACKUP_INFO)

# Clean source directory first to ensure we don't back up e.g. build artifacts.
clean "$SRC_DIR"

# Unlock LUKS device and mount.
echo "$DISK_PASSWORD" | sudo cryptsetup open $DEVICE $DEVICE_NAME -
sudo mkdir -p $MOUNT_DIR
sudo mount /dev/mapper/$DEVICE_NAME $MOUNT_DIR

# Back up data dir via restic (local).
echo "Starting local restic backup..."
restic -r $DST_DIR_LOCAL --verbose backup $SRC_DIR

# Unmount and lock LUKS device.
sudo umount $MOUNT_DIR
sudo cryptsetup close $DEVICE_NAME

# Back up data dir via restic/rclone (remote)
echo "Starting remote restic backup..."
restic -r $DST_DIR_REMOTE --verbose backup $SRC_DIR

