#!/usr/bin/env bash

# These mime types will be opened via xdg-open instead of vim.
XDG_OPEN_MIME_TYPES=(
    'application/pdf'
    'application/xhtml+xml'
    'text/html'
    'image/jpeg'
    'image/png'
    'image/gif'
    'image/svg'
    'image/svg+xml'
    'audio/mpeg'
    'audio/x-wav'
    'audio/x-vorbis+ogg'
    'video/mp4'
    'video/webm'
)

while getopts "hg" opt; do
    case $opt in
        g)
            USE_GREP=1
            ;;
        h | *)
            echo "Usage: open [-h] [-g] [<path>]"
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))

# If -g option is passed, search by file contents rather than file names.
START_DIR=~
if [ -v USE_GREP ]; then
    if [ -n "$1" ]; then
        if [ ! -d "$1" ]; then
            echo "Error: path must be directory when using -g"
            exit 1
        fi
        START_DIR=$1
    fi
    OPEN_PATH=$(rg . "$START_DIR" | fzf | cut -d: -f1)
# If directory argument is specified, interpret as starting directory (default
# to home otherwise). If file argument is specified, open it directly either
# via xdg-open or nvim
elif [ -n "$1" ]; then
    if [ -d "$1" ]; then
        START_DIR=$1
    else
        OPEN_PATH=$1
    fi
fi

# Get the path to the file/directory to be opened via fzf, if not already
# specified. Skip this if the grep (-g) option was passed, as we want to avoid
# the user exiting the grep fzf early and then initiating this fzf as well.
if [ -z "$OPEN_PATH" ] && [ ! -v USE_GREP ]; then
    OPEN_PATH=$(fd . "$START_DIR" | fzf --preview='bat --color=always {}')
fi

# If the path is empty (e.g. fzf exited early), exit early.
if [ -z "$OPEN_PATH" ]; then
    exit 0
fi

if [ -d "$OPEN_PATH" ]; then
    # Open directories via graphical file explorer.
    xdg-open "$OPEN_PATH"
else
    # For files, check mime type to see whether we should open it via xdg-open.
    OPEN_PATH_MIME_TYPE=$(xdg-mime query filetype "$OPEN_PATH")
    for ((i=0;i<${#XDG_OPEN_MIME_TYPES[@]};i++)); do
        if [ "$OPEN_PATH_MIME_TYPE" = "${XDG_OPEN_MIME_TYPES[${i}]}" ]; then
            xdg-open "$OPEN_PATH"
            exit 0
        fi
    done

    # If not an xdg-open mime type, just open in vim by default.
    nvim "$OPEN_PATH"
fi
