#!/usr/bin/env python3

import argparse
import os
import random

parser = argparse.ArgumentParser()
parser.add_argument('directory', nargs='?', help='wallpaper directory')
args = parser.parse_args()

start = args.directory if args.directory else os.getcwd()
files = [f.path for f in os.scandir(start) if f.is_file()]
wallpaper = random.choice(files)

os.system(f'gsettings set org.gnome.desktop.background picture-uri-dark file://{wallpaper}')
